[build]
  publish = "dist"
  command = "npm run build"
[[redirects]]
  from = "/nextimg*"
  query = { url = ":url", w = ":width", q = ":quality" }
  to = "/.netlify/functions/image?url=:url&w=:width&q=:quality"
  status = 200
